### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by MrMoronIV** [alerta/sensu-alerta#3]
`{"timestamp":"2018-03-04T19:17:52.217423+0100","level":"error","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/alerta.rb","name":"alerta"},"event":{"id":"a53fb85f-69b8-47a2-841c-0d481f7ceedf"},"output":["Unexpected error: Broken pipe"]}`

Any ideas? Tried to figure it out but have no idea how to solve this....

**Comment by tester22** [comment]
This worked for me:
https://github.com/sensu/sensu/issues/1003#issuecomment-123394757
